// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKcAdRWyiMk9-CAVO4GBmBoREVT6VbmgY',
    appId: '1:893467265429:web:7b6317c77d02f0e7020e9c',
    messagingSenderId: '893467265429',
    projectId: 'fasum-d96d5',
    authDomain: 'fasum-d96d5.firebaseapp.com',
    storageBucket: 'fasum-d96d5.firebasestorage.app',
    measurementId: 'G-2GVL7BFFXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWox6OB3_Cl1GO5WSrMSp5tSKVfM3iAA',
    appId: '1:893467265429:android:8150e6a9d2f3f54b020e9c',
    messagingSenderId: '893467265429',
    projectId: 'fasum-d96d5',
    storageBucket: 'fasum-d96d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8nAZAL38qsWD1JyGbRDD2E7tgOB8r2M',
    appId: '1:893467265429:ios:7abfa87c62a39c16020e9c',
    messagingSenderId: '893467265429',
    projectId: 'fasum-d96d5',
    storageBucket: 'fasum-d96d5.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN8nAZAL38qsWD1JyGbRDD2E7tgOB8r2M',
    appId: '1:893467265429:ios:7abfa87c62a39c16020e9c',
    messagingSenderId: '893467265429',
    projectId: 'fasum-d96d5',
    storageBucket: 'fasum-d96d5.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKcAdRWyiMk9-CAVO4GBmBoREVT6VbmgY',
    appId: '1:893467265429:web:905613b07229aa8e020e9c',
    messagingSenderId: '893467265429',
    projectId: 'fasum-d96d5',
    authDomain: 'fasum-d96d5.firebaseapp.com',
    storageBucket: 'fasum-d96d5.firebasestorage.app',
    measurementId: 'G-RBF6WHJ7H8',
  );
}
